version: '2'

networks:
  net-registry:
    driver: bridge

services:
  registry:
    image: 'registry:2.5.1'
    networks:
      - net-registry
    ports:
      - 5000:5000
    user: root
    environment:
      - REGISTRY_HTTP_NET=tcp
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
    volumes:
      - ./registry:/var/lib/registry
      - ./certs:/certs
    restart: always
